name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.0', '3.1.x', '5.0.x' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      working-directory: RestaurantAPI
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
    - working-directory: RestaurantAPI
      run: dotnet restore
    - name: Build
    - working-directory: RestaurantAPI
      run: dotnet build --configuration Release --no-restore
    - name: Test
    - working-directory: RestaurantAPI
      run: dotnet test --no-restore --verbosity normal
